# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe90c1bd47e3f039f59d82d4dbc6ace4fea992e495d655f324ca615ae76d0dab30e5d17c043e96eee60c406fa14dffbcdd64c240871be12a091e441e1b62378a

test:
  secret_key_base: dbbf4bfad8a341544497c178c6734b34f1050d25bf60d9e9fc8422b344e59725f69243cc940cef188c59ed1423ef9b5ad3c6f1afb70c899ccefdf33c41ec5fcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
